# Generated by Django 4.2.17 on 2024-12-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='devicetype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fcmtoken',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
