# Generated by Django 4.2.23 on 2025-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='qms',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='qmsresponse',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
    ]
