# Generated by Django 4.2.23 on 2025-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite_management', '0003_alter_cms_status_alter_faq_status_alter_qms_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='qms',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='qmsresponse',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50),
        ),
    ]
