# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite_management', '0004_alter_cms_status_alter_faq_status_alter_qms_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms',
            name='user_type',
            field=models.CharField(
                blank=True,
                choices=[('client', 'Client'), ('provider', 'Service Provider')],
                max_length=20,
                null=True,
            ),
        ),
    ]
