"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import environ
import firebase_admin
import firebase_admin.firestore
import firebase_admin.firestore_async
from csp.constants import NONE, SELF
from firebase_admin import credentials

env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@30x)4m8pomq1$$t(0q)x(z_)cxupioj7ig1+9^+bynxwrjze^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [

    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "customuser",
    "profile_management.apps.ProfileManagementConfig",
    'rest_framework',
    'rest_framework.authtoken',
    'project_management',
    "adminsite_management",
    "master",
    "content_management",
   'drf_yasg','chat_management','channels',
   "csp",

]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.SubscriptionAwareTokenAuthentication',
    ],
       'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}
CORS_ALLOWED_ORIGINS = [
    "http://localhost:14334",
    "http://127.0.0.1:14334",
    "http://192.168.6.22:14334",
    "http://localhost:14208",
    "http://127.0.0.1:14208",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8001",
    "http://127.0.0.1:8000",
    "https://trustwork-dev.dedicateddevelopers.us",
    "https://trustwork.live",
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:14334",
    "http://127.0.0.1:14334",
    "http://192.168.6.22:14334",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8001",
    "https://trustwork-dev.dedicateddevelopers.us",
    "https://trustwork-api.dedicateddevelopers.us",
    "https://trustwork-escrow.dedicateddevelopers.us",
    "https://trustwork.live",
    "https://api.trustwork.live",
    "https://escrow.trustwork.live",
    "https://*.ngrok-free.app",
    "https://*.ngrok.app",
    "https://*.dedicateddevelopers.us",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'core.middlewares.reponse_middleware.ResponseMiddleware',
    'core.middlewares.renderer_middleware.CustomFinalResponseMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "csp.middleware.CSPMiddleware",
    "core.middlewares.permissions_policy_middleware.PermissionsPolicyMiddleware",
]
CORS_ALLOW_ALL_ORIGINS=True
ROOT_URLCONF = 'core.urls'


CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'idempotency-key',
    'ngrok-skip-browser-warning',
    'x-access-token',
    'x-csrftoken',
    'x-requested-with',
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
# ASGI_APPLICATION = 'core.asgi.application'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Stripe settings
STRIPE_TEST_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY")
STRIPE_TEST_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_SUBSCRIPTION_WEBHOOK_SECRET = os.getenv("STRIPE_SUBSCRIPTION_WEBHOOK_SECRET")
BASE_FRONTEND_URL="http://localhost:8000"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     },
# }


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USERNAME'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'customuser.CustomUser'

AUTHENTICATION_BACKENDS = ['customuser.backends.EmailBackend', 'customuser.backends.PhoneBackend']

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD =env("EMAIL_HOST_PASSWORD")

# Default email for sending OTP
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
try:
    OTP_VALIDITY_MINUTES = int(os.getenv("OTP_VALIDITY_MINUTES", "10") or 10)
except (TypeError, ValueError):
    OTP_VALIDITY_MINUTES = 10

try:
    WEBSITE_SUBSCRIPTION_PENDING_TTL_MINUTES = int(
        os.getenv("WEBSITE_SUBSCRIPTION_PENDING_TTL_MINUTES", "30") or 30
    )
except (TypeError, ValueError):
    WEBSITE_SUBSCRIPTION_PENDING_TTL_MINUTES = 30

PAYMENT_RECEIPT_EMAIL_ENABLED = (
    os.getenv("PAYMENT_RECEIPT_EMAIL_ENABLED", "True").strip().lower()
    not in {"0", "false", "no", "off"}
)

# FIREBASE_CREDENTIALS = credentials.Certificate("/home/webskitters/Desktop/Projects/trustwork-backend/credentials/ServiceAccountKey.json")
# firebase_admin.initialize_app(FIREBASE_CREDENTIALS, {
#     "databaseURL": "https://your-project-id.firebaseio.com/"
# })

cred = credentials.Certificate("./credentials/ServiceAccountKey.json")
firebase_admin.initialize_app(cred)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if DEBUG:
    # Local/dev mode
    SECURE_SSL_REDIRECT = False     # don’t force HTTPS in dev
    SESSION_COOKIE_SECURE = False   # cookies can be sent over HTTP
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0         # disable HSTS in dev
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
else:
    # Production
    SECURE_SSL_REDIRECT = True      # force HTTPS
    SESSION_COOKIE_SECURE = True    # secure cookies
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Security headers
# SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# CSP (django-csp style!)
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": (NONE,),   # block everything by default
        "script-src": (SELF, "https://cdn.jsdelivr.net"),
        "style-src": (SELF, "https://cdn.jsdelivr.net"),
        "img-src": (SELF, "data:"),
        "media-src": (SELF,),            # allow audio/video from self (/media/)
        "object-src": (SELF,),   # allow PDFs, other embeds
        "frame-src": (SELF,),    # allow iframes from media
        "connect-src": (SELF,),
    }
}


# X-Frame-Options (same-origin is typical)
X_FRAME_OPTIONS = "SAMEORIGIN"

# Referrer Policy
SECURE_REFERRER_POLICY = "same-origin"
