# Generated by Django 4.2.16 on 2024-11-19 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_management', '0001_initial'),
        ('adminsite_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qms',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_management.profile'),
        ),
    ]
