# Generated by Django 4.2.19 on 2025-02-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0012_alter_previousworks_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
