"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from csp.constants import NONE, SELF
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jx!pq__53@&3vh&24r%23zarv1m+7kbsg&yr41d%c_3%+j(*je'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ["*"]

TRUSTWORK_BASE_API = os.getenv('TRUSTWORK_BASE_API')
ESCROW_BASE_API = os.getenv('ESCROW_BASE_API')
WEBHOOK_HOST=f'{ESCROW_BASE_API}/stripe/api/process-stripe-session/'
APPEND_SLASH=False

MTN_BASE_URL = os.getenv('MTN_BASE_URL')
MTN_COLLECTION_API_USER_ID = os.getenv('MTN_COLLECTION_API_USER_ID')
MTN_COLLECTION_API_KEY = os.getenv('MTN_COLLECTION_API_KEY')
MTN_DISBURSEMENT_API_USER_ID = os.getenv('MTN_DISBURSEMENT_API_USER_ID')
MTN_DISBURSEMENT_API_KEY = os.getenv('MTN_DISBURSEMENT_API_KEY')

MTN_COLLECTION_PRIMARY_KEY = os.getenv('MTN_COLLECTION_PRIMARY_KEY')
MTN_COLLECTION_SECONDARY_KEY = os.getenv('MTN_COLLECTION_SECONDARY_KEY')
MTN_DISBURSEMENT_PRIMARY_KEY = os.getenv('MTN_DISBURSEMENT_PRIMARY_KEY')
MTN_DISBURSEMENT_SECONDARY_KEY = os.getenv('MTN_DISBURSEMENT_SECONDARY_KEY')


STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PAYOUT_WEBHOOK_SECRET = os.getenv('STRIPE_PAYOUT_WEBHOOK_SECRET')
STRIPE_COLLECTION_WEBHOOK_SECRET = os.getenv('STRIPE_COLLECTION_WEBHOOK_SECRET')


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'escrow_management',
    'user_management',
    'rest_framework',
    'django_celery_results',
    "csp",
]

REST_FRAMEWORK = {

       'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "csp.middleware.CSPMiddleware",
    "core.middlewares.permissions_policy_middleware.PermissionsPolicyMiddleware",
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
CSRF_TRUSTED_ORIGINS = ['https://*.dedicateddevelopers.us','https://*.127.0.0.1','http://10.2.0.202:8000','https://10.2.0.202:8000']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('DB_NAME'), 
        'USER': env('DB_USERNAME'), 
        'PASSWORD': env('DB_PASSWORD'), 
        'HOST': env('DB_HOST'), 
        'PORT': env('DB_PORT'), 
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
# CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_TASK_IGNORE_RESULT = False

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # keep Django logs separate
    "formatters": {
        "default": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "subscription_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "subscription.log",   # separate log file
            "formatter": "default",
        },
        "webhook_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "webhook.log",   # separate log file
            "formatter": "default",
        },
        "disbursement_webhook_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "disbursement_webhook.log",   # separate log file
            "formatter": "default",
        },
        "task_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "celery_task.log",   # separate log file
            "formatter": "default",
        },
    },
    "loggers": {
        "escrow_management.views.initialize_subscription": {
            "handlers": ["subscription_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "payment_handler.payment_gateways.webhooks.MTN.collections_webhook": {
            "handlers": ["webhook_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "payment_handler.payment_gateways.webhooks.MTN.disbursement_webhook": {
            "handlers": ["disbursement_webhook_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "escrow_management.tasks": {
            "handlers": ["task_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if DEBUG:
    # Local/dev mode
    SECURE_SSL_REDIRECT = False     # don’t force HTTPS in dev
    SESSION_COOKIE_SECURE = False   # cookies can be sent over HTTP
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0         # disable HSTS in dev
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
else:
    # Production
    SECURE_SSL_REDIRECT = True      # force HTTPS
    SESSION_COOKIE_SECURE = True    # secure cookies
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Security headers
# SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# CSP (django-csp style!)
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": (NONE,),   # block everything by default
        "script-src": (SELF, "https://cdn.jsdelivr.net"),
        "style-src": (SELF, "https://cdn.jsdelivr.net"),
        "img-src": (SELF, "data:"),
        "connect-src": (SELF,),
    }
}

# X-Frame-Options (same-origin is typical)
X_FRAME_OPTIONS = "SAMEORIGIN"

# Referrer Policy
SECURE_REFERRER_POLICY = "same-origin"