"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ
env = environ.Env()
environ.Env.read_env(".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jx!pq__53@&3vh&24r%23zarv1m+7kbsg&yr41d%c_3%+j(*je'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

TRUSTWORK_BASE_API = os.getenv('TRUSTWORK_BASE_API')
ESCROW_BASE_API = os.getenv('ESCROW_BASE_API')
WEBHOOK_HOST=f'{ESCROW_BASE_API}/stripe/api/process-stripe-session/'
APPEND_SLASH=False

MTN_BASE_URL = os.getenv('MTN_BASE_URL')
MTN_COLLECTION_API_USER_ID = os.getenv('MTN_COLLECTION_API_USER_ID')
MTN_COLLECTION_API_KEY = os.getenv('MTN_COLLECTION_API_KEY')
MTN_DISBURSEMENT_API_USER_ID = os.getenv('MTN_DISBURSEMENT_API_USER_ID')
MTN_DISBURSEMENT_API_KEY = os.getenv('MTN_DISBURSEMENT_API_KEY')

MTN_COLLECTION_PRIMARY_KEY = os.getenv('MTN_COLLECTION_PRIMARY_KEY')
MTN_COLLECTION_SECONDARY_KEY = os.getenv('MTN_COLLECTION_SECONDARY_KEY')
MTN_DISBURSEMENT_PRIMARY_KEY = os.getenv('MTN_DISBURSEMENT_PRIMARY_KEY')
MTN_DISBURSEMENT_SECONDARY_KEY = os.getenv('MTN_DISBURSEMENT_SECONDARY_KEY')


STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PAYOUT_WEBHOOK_SECRET = os.getenv('STRIPE_PAYOUT_WEBHOOK_SECRET')
STRIPE_COLLECTION_WEBHOOK_SECRET = os.getenv('STRIPE_COLLECTION_WEBHOOK_SECRET')


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'escrow_management',
    'user_management',
    'rest_framework'
]

REST_FRAMEWORK = {

       'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
CSRF_TRUSTED_ORIGINS = ['https://*.dedicateddevelopers.us','https://*.127.0.0.1','http://10.2.0.202:8000','https://10.2.0.202:8000']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('DB_NAME'), 
        'USER': env('DB_USERNAME'), 
        'PASSWORD': env('DB_PASSWORD'), 
        'HOST': env('DB_HOST'), 
        'PORT': env('DB_PORT'), 
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # <- keep Django's logging separate
    "formatters": {
        "default": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "subscription_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "project_log.log",   # store in project root
            "formatter": "default",
        },
    },
    "loggers": {
        # Only your subscription view logger
        "escrow_management.views.initialize_subscription": {
            "handlers": ["subscription_file"],
            "level": "DEBUG",
            "propagate": False,   # <- prevents Django/urllib3 noise
        },
    },
}