# Generated by Django 4.2.17 on 2024-12-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0003_profile_year_of_experiance'),
        ('project_management', '0005_remove_feedback_rating_remove_feedback_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_feedback', to='profile_management.profile'),
        ),
    ]
