# Generated by Django 4.2.17 on 2024-12-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_alter_feedback_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('ongoing', 'ongoing'), ('completed', 'completed'), ('inactive', 'inactive'), ('block', 'block'), ('myoffer', 'myoffer')], default='active', max_length=50),
        ),
    ]
