# Generated by Django 4.2.17 on 2024-12-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_alter_bid_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_sent',
            field=models.BooleanField(default=True),
        ),
    ]
