# Generated by Django 4.2.17 on 2024-12-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_alter_project_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
