# Generated by Django 4.2.17 on 2025-01-06 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_management.project'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('collection', 'collection'), ('disbursement', 'disbursement')], default='collection', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.bid'),
        ),
    ]
