# Generated by Django 4.2.17 on 2025-01-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0015_transactions_project_transactions_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('ongoing', 'ongoing'), ('completed', 'completed'), ('inactive', 'inactive'), ('block', 'block'), ('myoffer', 'myoffer'), ('Rejected', 'Rejected')], default='active', max_length=50),
        ),
    ]
