# Generated by Django 4.2.16 on 2024-11-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_location_latitude_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
    ]
