# Generated by Django 4.2.17 on 2024-12-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_jobcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
