# Generated by Django 4.2.20 on 2025-04-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_contactus_facebook_url_contactus_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], max_length=20, null=True),
        ),
    ]
