# Generated by Django 4.2.20 on 2025-04-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_remove_contactus_map_url_contactus_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsconditionsdetails',
            name='terms_conditions_section',
        ),
        migrations.AddField(
            model_name='privacypolicysection',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termsconditionssection',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PrivacyPolicyDetails',
        ),
        migrations.DeleteModel(
            name='TermsConditionsDetails',
        ),
    ]
