# Generated by Django 4.2.20 on 2025-04-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_remove_termsconditionsdetails_terms_conditions_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyyoutrustussection',
            name='mission_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyyoutrustussection',
            name='mission_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whyyoutrustussection',
            name='vision_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whyyoutrustussection',
            name='vision_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='WhyYouTrustUsDetails',
        ),
    ]
