# Generated by Django 4.2.20 on 2025-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_whyyoutrustussection_mission_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='howitworksstep',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pricefeatures',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='whyyoutrustusfeature',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='contactus',
            name='map_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
