# Generated by Django 4.2.23 on 2025-07-31 14:51
# Generated by Django 4.2.23 on 2025-07-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0009_aboutus_created_at_aboutus_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
