# Generated by Django 4.2.20 on 2025-08-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0010_pricingplan_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howitworkssection',
            name='image',
        ),
        migrations.AddField(
            model_name='howitworkssection',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='home_page/how_it_works/'),
        ),
    ]
