# Generated by Django 4.2.20 on 2025-08-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0011_remove_howitworkssection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='instagram_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
