# Generated by Django 4.2.20 on 2025-08-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0012_contactus_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
