# Generated by Django 4.2.16 on 2024-11-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.CharField(blank=True, help_text='Latitude', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(blank=True, help_text='Longitude', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.TextField(),
        ),
    ]
