# Generated by Django 4.2.16 on 2024-11-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_location_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
