# Generated by Django 4.2.16 on 2024-12-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_location_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
