# Generated by Django 4.2.23 on 2025-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_location_code_alter_location_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
    ]
