# Generated by Django 4.2.23 on 2025-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_jobcategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50),
        ),
    ]
