# Generated by Django 4.2.16 on 2024-11-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0002_profile_location_profile_project_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year_of_experiance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
