# Generated by Django 4.2.17 on 2024-12-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0003_profile_year_of_experiance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications_enabled',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=50),
        ),
    ]
