# Generated by Django 4.2.17 on 2024-12-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0004_profile_notifications_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications_enabled',
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
