# Generated by Django 4.2.17 on 2025-01-09 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0005_remove_profile_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50)),
                ('subscription_frequency', models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=100)),
                ('subscription_plan', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_subscription', to='profile_management.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
