# Generated by Django 4.2.17 on 2025-01-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0006_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
