# Generated by Django 4.2.18 on 2025-01-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0008_bankdetails_routing_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='ifsc_code',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
