# Generated by Django 4.2.20 on 2025-04-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0013_profile_phone_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
