# Generated by Django 4.2.20 on 2025-05-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0014_alter_profile_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='purchase_token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
