# Generated by Django 4.2.21 on 2025-05-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0016_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='expire_date',
        ),
    ]
