# Generated by Django 4.2.21 on 2025-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0017_remove_coupons_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='purchase_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
