# Generated by Django 4.2.21 on 2025-05-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0018_alter_subscriptions_purchase_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReferContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50)),
                ('content', models.TextField()),
                ('icon', models.ImageField(null=True, upload_to='app_refer/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
