# Generated by Django 4.2.21 on 2025-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0019_apprefercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='bank_account_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
