# Generated by Django 4.2.23 on 2025-07-09 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0022_bankdetails_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='onboarding_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_experiance',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profilemembership',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
