# Generated by Django 4.2.21 on 2025-05-29 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0022_bankdetails_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemembership',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
