# Generated by Django 4.2.21 on 2025-06-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0023_alter_profilemembership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='onboarding_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
