# Generated by Django 4.2.23 on 2025-06-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0024_bankdetails_onboarding_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year_of_experiance',
            field=models.TextField(default=0, null=True),
        ),
    ]
