# Generated by Django 4.2.23 on 2025-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0025_alter_profile_year_of_experiance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
    ]
