# Generated by Django 4.2.23 on 2025-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0026_subscriptions_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprefercontent',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='membershipplans',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='previousworks',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='profilemembership',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
    ]
