# Generated by Django 4.2.23 on 2025-08-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0023_bankdetails_onboarding_token_subscriptions_expire_at_and_more'),
        ('profile_management', '0028_alter_apprefercontent_status_and_more'),
    ]

    operations = [
    ]
