# Generated by Django 4.2.30 on 2026-05-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0029_merge_20250801_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50)),
                ('provider', models.CharField(choices=[('mtn', 'MTN MoMo'), ('orange', 'Orange Money'), ('stripe', 'Stripe')], max_length=20)),
                ('reference_id', models.CharField(max_length=255, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('subscription_frequency', models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('pricing_plan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField()),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payment_attempts', to='profile_management.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'payment_status', 'expires_at'], name='profile_man_profile_8f03fb_idx'), models.Index(fields=['provider', 'reference_id'], name='profile_man_provide_e4d250_idx')],
            },
        ),
    ]
