# Generated by Django 4.2.30 on 2026-06-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0030_subscription_payment_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='receipt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='receipt_currency',
            field=models.CharField(default='XAF', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='receipt_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='receipt_payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
