# Generated by Django 4.2.17 on 2024-12-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_customuser_devicetype_customuser_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referred_by_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_referal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
