# Generated by Django 4.2.18 on 2025-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_customuser_total_referal_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_referal_amount',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_referal_count',
            field=models.TextField(default=0, null=True),
        ),
    ]
