# Generated by Django 4.2.18 on 2025-02-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_alter_customuser_total_referal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_user_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
