# Generated by Django 4.2.18 on 2025-02-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_customuser_is_user_active_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_user_active',
            field=models.BooleanField(default=False),
        ),
    ]
