# Generated by Django 4.2.21 on 2025-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0009_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
