# Generated by Django 4.2.20 on 2025-08-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0010_customuser_is_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
