# Generated by Django 4.2.16 on 2024-12-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_project_city_project_country_project_state_and_more'),
        ('chat_management', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.project', unique=True),
        ),
    ]
