# Generated by Django 4.2.17 on 2024-12-05 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0003_conversation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
    ]
