# Generated by Django 4.2.21 on 2025-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0008_attatchment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
