# Generated by Django 4.2.21 on 2025-05-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0009_notification_object_id_notification_object_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='object_id',
            new_name='bid_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
