# Generated by Django 4.2.20 on 2025-04-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_header', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='aboutus_page/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='aboutus_page/')),
            ],
        ),
        migrations.CreateModel(
            name='AppDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playstore_link', models.URLField(blank=True, null=True)),
                ('appstore_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_header', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('call_center_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('map_url', models.TextField(blank=True, null=True)),
                ('get_in_touch_title', models.CharField(blank=True, max_length=255, null=True)),
                ('get_in_touch_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HowItWorksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_page/how_it_works/')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_header', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_title', models.CharField(blank=True, default='GET STARTED', max_length=255, null=True)),
                ('button_link', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_page/')),
            ],
        ),
        migrations.CreateModel(
            name='TermsConditionsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_header', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyYouTrustUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_header', models.CharField(blank=True, max_length=255, null=True)),
                ('section_description', models.TextField(blank=True, null=True)),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='aboutus_page/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutus_page/')),
            ],
        ),
        migrations.CreateModel(
            name='WhyYouTrustUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='aboutus_page/')),
                ('why_you_trust_us_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_you_trust_us_feature', to='content_management.whyyoutrustussection')),
            ],
        ),
        migrations.CreateModel(
            name='WhyYouTrustUsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('why_you_trust_us_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_you_trust_us_details', to='content_management.whyyoutrustussection')),
            ],
        ),
        migrations.CreateModel(
            name='TermsConditionsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms_conditions_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='content_management.termsconditionssection')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('contact_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_us_entries', to='content_management.contactus')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('privacy_policy_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_policy', to='content_management.privacypolicysection')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pricingplan_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='content_management.pricingplansection')),
            ],
        ),
        migrations.CreateModel(
            name='PriceFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.TextField(blank=True, null=True)),
                ('is_active', models.CharField(default=True, max_length=100)),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_features', to='content_management.pricingplan')),
            ],
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='home_page/how_it_works/')),
                ('howitworks_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='content_management.howitworkssection')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='home_page/features/')),
                ('feature_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='content_management.featuresection')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_page/')),
                ('app_download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_download_links', to='content_management.appdownload')),
            ],
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_page/')),
                ('app_download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_links', to='content_management.appdownload')),
            ],
        ),
    ]
