# Generated by Django 4.2.20 on 2025-04-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='facebook_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='x_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='youtube_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
