# Generated by Django 4.2.20 on 2025-04-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_pricingplan_billing_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='map_url',
        ),
        migrations.AddField(
            model_name='contactus',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
