# Generated by Django 4.2.16 on 2024-11-19 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_management', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_title', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('project_address', models.TextField()),
                ('project_budget', models.FloatField()),
                ('project_timeline', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('ongoing', 'ongoing'), ('completed', 'completed'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='profile_management.profile')),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.jobcategory')),
                ('project_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50)),
                ('bid_details', models.TextField()),
                ('quotation_details', models.TextField()),
                ('project_total_cost', models.TextField()),
                ('time_line', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='project_management.project')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_management.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
