# Generated by Django 4.2.16 on 2024-11-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0002_profile_location_profile_project_delete_chat'),
        ('master', '0002_location_latitude_location_longitude_and_more'),
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_hrs_week',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.jobcategory'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='project_management.project')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_management.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
