# Generated by Django 4.2.16 on 2024-11-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_project_project_hrs_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time_line_hour',
            field=models.TextField(null=True),
        ),
    ]
