# Generated by Django 4.2.17 on 2024-12-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_management', '0005_remove_profile_notifications_enabled_and_more'),
        ('project_management', '0007_project_bid_count_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_bid', to='profile_management.profile'),
        ),
    ]
