# Generated by Django 4.2.17 on 2024-12-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0010_bid_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='can_send_bid',
            field=models.BooleanField(default=False),
        ),
    ]
