# Generated by Django 4.2.17 on 2024-12-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0011_project_can_send_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
