# Generated by Django 4.2.21 on 2025-06-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0018_project_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
