# Generated by Django 4.2.21 on 2025-06-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0019_transactions_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='stripe_id',
        ),
    ]
