# Generated by Django 4.2.23 on 2025-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0019_currency_transactions_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, default='normal', max_length=50, null=True),
        ),
    ]
