# Generated by Django 4.2.23 on 2025-06-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0020_remove_transactions_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50)),
                ('xaf_currency', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
