# Generated by Django 4.2.23 on 2025-06-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0021_currency_transactions_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='xaf_currency',
            field=models.CharField(blank=True, null=True),
        ),
    ]
