# Generated by Django 4.2.23 on 2025-08-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0024_alter_bid_status_alter_currency_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, default='normal', max_length=50, null=True),
        ),
    ]
