# Generated by Django 4.2.23 on 2025-08-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0020_project_project_type'),
        ('project_management', '0025_project_project_type'),
    ]

    operations = [
    ]
