# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_management", "0025_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="external_order_id",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="gateway_transaction_id",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transactions",
            name="payment_token",
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
