# Generated by Django 4.2.24 on 2026-05-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0026_merge_20250801_0958'),
        ('project_management', '0026_transactions_orange_references'),
    ]

    operations = [
    ]
