# Generated by Django 4.2.30 on 2026-06-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0027_merge_20260515_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receipt_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
