# Generated by Django 4.2.17 on 2024-12-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0004_notification_created_at_notification_has_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
