# Generated by Django 4.2.17 on 2024-12-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0005_alter_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
