# Generated by Django 4.2.18 on 2025-01-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0007_chatroom_messages_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attatchment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('block', 'block')], default='active', max_length=50)),
                ('file', models.FileField(upload_to='chatroom/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_management.messages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
