# Generated by Django 4.2.23 on 2025-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0010_rename_object_id_notification_bid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attatchment',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='messages',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('deleted', 'deleted'), ('block', 'block')], default='active', max_length=50),
        ),
    ]
